import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/ui/navbar';
import Sidebar from './components/ui/sidebar';
import Footer from './components/ui/footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className='flex min-h-screen flex-col'>
          {' '}
          {/* Main container */}
          <div className='flex-grow'>
            {' '}
            {/* This div takes up available space */}
            <div className='flex'>
              <Sidebar />
              <main className='flex-1 p-4'>{children}</main>
            </div>
          </div>
          <Footer /> {/* Footer will stick to the bottom */}
        </div>
      </body>
    </html>
  );
}
